USERS = dict(MG=["mona gao", "mona", "MG", 'mg'],
             JB=["jim bao", "jim", "JB", 'jb'],
             TK=["terence khoo", "terence", "TK", "tk"],
             MC=["marc chalfin", "marc", "MC", "mc"],
             SK=["sonya kim", "sonya", "SK", "sk"],
             SB=["sumeet bhalla", "sumeet", "SB", "sb"],
             OK=["ocima kamboj", "ocima", "OK", "ok"],
             BM=["barsendu mukherjee", "barsendu", "BM", "bm"],
             PS=["pavithra srinivasan", "pavithra", "PS", "ps"],
             PP=["prashant pal", "prashant", "PP", "pp"],
             AA=["amar anand", "amar", "AA", "aa"],
             PA=["pulkit agarwal", "pulkit", "PA", "pa"],
             DH=["daniel hui", "daniel", "DH", "dh"],
             GG=["gaurav gupta", "gaurav", "GG", "gg"],
             SM=["suhail mohiuddin", "suhail", "SM", "sm"]
             )


USERS_EMAILS = dict(MG="mgao@auroim.com",
                    JB="jbao@auroim.com",
                    TK="tkhoo@auroim.com",
                    MC="mchalfin@auroim.com",
                    SK="skim@auroim.com",
                    SB="sbhalla@auroim.com",
                    OK="ocimakamboj@gmail.com",
                    BM="bmukherjee@auroim.com",
                    PS="pavithra@auroim.com@gmail.com",
                    PP="ppal@auroim.com",
                    AA="aanand@auroim.com",
                    PA="pagarwal@@auroim.com",
                    DH="dhui@@auroim.com",
                    GG="ggupta@auroim.com")